# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'rho_aux function
#'
#'Auxiliary function to compute rho
#'@param t numeric vector.
#'@param c tunning constant.
rho_aux <- function(t, c) {
    .Call('_ktaucenterscpp_rho_aux', PACKAGE = 'ktaucenterscpp', t, c)
}

#'rho_opt function
#'
#' An implementation of quasi optimal rho functions following reference [1]
#'
#'@param t numeric vector.
#'@param c tunning constant.
#'@return rho(\code{t}/\code{c}\code{c})
#'@examples val <- rho_opt(t = 0.5, c = 1.0)
#'@references [1] Salibian-Barrera, M., Willems, G., & Zamar,
#'   R. (2008). The fast-tau estimator for regression. Journal of
#'   Computational and Graphical Statistics, 17(3), 659-682.
#'
#'@export
rho_opt <- function(t, c) {
    .Call('_ktaucenterscpp_rho_opt', PACKAGE = 'ktaucenterscpp', t, c)
}

