# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'rho_opt function
#'
#' An implementation of quasi optimal rho functions following reference [1]
#'
#'@param t numeric vector.
#'@param c tunning constant.
#'@return rho(\code{t}/\code{c})
#'@examples val <- rho_opt(t = 0.5, c = 1.0)
#'@references [1] Salibian-Barrera, M., Willems, G., & Zamar,
#'   R. (2008). The fast-tau estimator for regression. Journal of
#'   Computational and Graphical Statistics, 17(3), 659-682.
#'
#'@export
rho_opt <- function(t, c) {
    .Call('_ktaucenterscpp_rho_opt', PACKAGE = 'ktaucenterscpp', t, c)
}

#'psi_opt function
#'
#' An implementation of the derivative of quasi optimal rho function
#'
#'@param t a numeric vector
#'@param c a tunning constant.
#'@return psi(\code{t}/ \code{c})
#'@examples val <- psi_opt(t = 0.5, c = 1)
#'
#'@export
psi_opt <- function(t, c) {
    .Call('_ktaucenterscpp_psi_opt', PACKAGE = 'ktaucenterscpp', t, c)
}

#' derpsiOpt
#' the derivative of the psi function
#'
#' @param t a numeric vector
#' @param c a tunning constant.
#' @return rho'(\code{x}/ \code{c})
#' @examples val <- derpsi_opt(t = 0.5, c = 1.0)
#'
#' @export
derpsi_opt <- function(t, c) {
    .Call('_ktaucenterscpp_derpsi_opt', PACKAGE = 'ktaucenterscpp', t, c)
}

